spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/product}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
server.port=${PORT:8080}
viacep.base-url=${VIACEP_BASE_URL:https://viacep.com.br/ws}
viacep.connect-timeout-ms=${VIACEP_CONNECT_TIMEOUT_MS:2000}
viacep.read-timeout-ms=${VIACEP_READ_TIMEOUT_MS:3000}
